### ISSUE TITLE
Contacting SWATHatlas Team Not Explained

### ISSUE THREAD

**Issue by DarioS** [OpenSWATH/documentation#1]
The documentation webpage recommends "For technical help with the libraries, please contact the SWATHAtlas team." But, there's no hyperlink to a webpage containing the team's contact details. Also, the navigation bar on the left side of the SWATHAtlas website contains no Contact Us section, so neither the OpenSWATH documentation nor the SWATHAtlas website provide any contact details.

**Comment by grosenberger** [comment]
Thanks for the note, I have updated the [documentation](http://openswath.org/en/latest/docs/swathatlas.html) accordingly.
