### ISSUE TITLE
openswath2.4.0 There were not enough bins with the minimal number of peptides

### ISSUE THREAD

**Issue by Allen188** [OpenSWATH/documentation#15]
When I run openswath2.4.0,  I encountered an error : Unexpected internal error (There were not enough bins with the minimal number of peptides). Is there any parameter that can be adjusted?

**Comment by grosenberger** [comment]
``OpenSwathWorkflow --helphelp`` will show all options. ``-RTNormalization:MinBinsFilled`` is the one you could try first.

**Comment by Allen188** [comment]
sorry, the problem is still not solved,  but in the same file, we did not encounter this problem in the old OpenSWATH version(2.0.0), we can successfully export the Pyprophet result

**Comment by grosenberger** [comment]
How many normalization peptides are you using? And are you missing many of those? If you set the MinBinsFilled value to a lower number, eventually the RT normalization should work.

**Comment by Allen188** [comment]
-RTNormalization:MinBinsFilled 5 ,We found the cause of the error, the file is from sciex 6600, we set parameters - irt_mz_extraction_window to 20, when we change to 50,  running successfully, thank you very much for your help
