### ISSUE TITLE
Percolator Documentation Contains PyProphet Commands

### ISSUE THREAD

**Issue by DarioS** [OpenSWATH/documentation#8]
In the Tutorial section of the Percolator adapter documentation, there are a couple of commands shown for PyProphet. Is this an unintentional copy of the instructions from the PyProphet documentation?

**Comment by grosenberger** [comment]
No, this is correct, since some functionality (e.g. protein-level FDR control, exporting or IPF) is only available in PyProphet. Since most parts are compatible, it's however possible to apply these functions after PercolatorAdapter.

**Comment by DarioS** [comment]
Now I understand.
